server:
  port: 9090
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:weatherdb}
    username: ${DB_LOGIN:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

api-url: "https://api.telegram.org/"
webhook-path: "https://36e2-92-124-163-11.eu.ngrok.io"
bot-name: "Local22WeatherBot"
bot-token: "5904869702:AAHHYUDLy2xE_-Hh83J3NYuXLRBa5c-Lei8"
apiLineUrl: "https://api.open-meteo.com/v1/forecast?"
request: "&daily=temperature_2m_max,temperature_2m_min,windspeed_10m_max,winddirection_10m_dominant&current_weather=true&timezone="
api-geo-url: "https://api.geoapify.com/v1/geocode/reverse?"
api-geo-key: "&format=json&apiKey=2273a270279f43d8bc633603b74385b9"


